### ISSUE TITLE
Fix the logic for computing the set of files to verify

### ISSUE THREAD

**Issue by brianaydemir** [HTPhenotyping/htcondor_file_transfer#40]
As a comment left by Josh notes:

```
# TODO: rethink this logic for push vs. pull
# Check for files that we have already verified, and do not verify them again.
```

Now that we have a real need to use this utility to *push* files, we need to follow up on this remark. The current logic fails when the destination has files that are not present at the source. (There may be other failure modes, as well.) For example:

```
Traceback (most recent call last):
  File "/home/brian.aydemir/2022-08-15/spool/xfer.py", line 1367, in <module>
    main()
  File "/home/brian.aydemir/2022-08-15/spool/xfer.py", line 1311, in main
    dry_run=args.dry_run,
  File "/home/brian.aydemir/2022-08-15/spool/xfer.py", line 660, in write_inner_dag
    bytes_to_verify = sum(src_files[fname] for fname in files_to_verify)
  File "/home/brian.aydemir/2022-08-15/spool/xfer.py", line 660, in <genexpr>
    bytes_to_verify = sum(src_files[fname] for fname in files_to_verify)
KeyError: PosixPath('job')
```

**Comment by brianaydemir** [comment]
As best as I can tell, "verification" handles the case where a file spontaneously shows up at both the source and destination.

It should be okay to ignore files that spontaneously show up only at the destination.
